services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_AUTH_API_BASE_URL: ${NEXT_PUBLIC_AUTH_API_BASE_URL}
        NEXT_PUBLIC_PG_REGISTRY_API_BASE_URL: ${NEXT_PUBLIC_PG_REGISTRY_API_BASE_URL}
        NEXT_PUBLIC_PAYMENTS_API_BASE_URL: ${NEXT_PUBLIC_PAYMENTS_API_BASE_URL}
        NEXT_PUBLIC_MONGO_FACTORY_API_BASE_URL: ${NEXT_PUBLIC_MONGO_FACTORY_API_BASE_URL}
        NEXT_PUBLIC_MONGO_FACTORY_API_ADMIN_KEY: ${NEXT_PUBLIC_MONGO_FACTORY_API_ADMIN_KEY}
        NEXT_PUBLIC_RAZORPAY_KEY_ID: ${NEXT_PUBLIC_RAZORPAY_KEY_ID}
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
        NEXT_PUBLIC_PAYPAL_CLIENT_ID: ${NEXT_PUBLIC_PAYPAL_CLIENT_ID}
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      HOSTNAME: "0.0.0.0"
      NODE_ENV: "production"
    init: true
    restart: unless-stopped
